FinalProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include("tinyurl.urls"), name='tinyurl'),
]

tinyurl/urls.py

from django.urls import path, include, re_path
from . import views
app_name = "tinyurl"

urlpatterns = [
    path('', views.index, name='index'),
    path('redirect/', views.re_direct_url, name='redirect'),
    path('makeshort/', views.shorten_url, name='shorten_url'),
]







tinyurl/models.py
from django.db import models

# Create your models here.


class Urls(models.Model):
    short_id = models.CharField(max_length=250)
    httpurl = models.URLField(max_length=250)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.httpurl

tinyurl/views.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.conf import settings
from django.http import HttpResponse
from .models import Urls
import json
from contextualizer import context_manager


# Create your views here.
def index(request):
    return render(request, 'tinyurl/index.html')

def re_direct_url(request, urls_id):
    url = get_object_or_404(Urls, pk=urls_id)
    url.count = url.count+1
    url.save()
    return redirect(url.httpurl)

def shorten_url(request):
    url = request.POST.get("url", '')
    if not (url == ''):
        request_content = context_manager.get_context_from_article(url)
        request_content_join = '-'.join(request_content)
        b = Urls(httpurl=url, short_id=request_content_join)
        b.save()
        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + request_content_join
        print(response_data)
        return HttpResponse(json.dumps(response_data), content_type="application/json")

    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")



tinyurl/templates/tinyurl/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>tinyurl</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'tinyurl:index' %}">TinyUrl</a>
            </div>
        </div>
    </nav>
</body>
<script type="text/javascript">
 $(function() {
 $('#submitButton').click(function() {
 $.ajax({
 type: "POST",
 url: "/makeshort/",
 data: {
 'url' : $('#url').val(),
 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
 },
 success: returnSuccess,
 dataType: 'json'
 });
 });
});

function returnSuccess(data) {
 if(data.url) {
 $('#url-result').text(data.url);
 $('#url').val("");
 } else {
 $('#url-result').text("Do not submit blank.");
 }

}
</script>


{% block body %}
{% endblock %}
</html>

tinyurl/templates/tinyurl/index.html
{% extends 'tinyurl/base.html' %}
{% block body %}

<div class="container h-100 d-flex justify-content-center">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-sm-9">
                <input type="text" name="url" id="url" class="form-control input-sm" placeholder="https://timesofindia.indiatimes.com/" />
            </div>
            <div class="col-sm-3">
                {% csrf_token %}
            <button id="submitButton" class="btn btn-primary">Submit</button></p>
            </div>
        </div>
    <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
</div>
</div>

{% endblock %}